config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :fav_items
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

#The code between these two comments is correct! Make a note of it!
resources :pages

#get 'home' => 'pages#home'
get 'home' => 'items#home'

#1:33pm 8/5/21: Find the correct bloody action to put here!!!!!!!!!

#root 'pages#home'
#The code between these two comments is correct! Make a note of it!

#root :to => "pages#home"
root :to => "items#home"




#get 'home' => 'pages#home'
#root 'home' => 'pages#home'


#root 'pages#home'

#get 'home', to:'pages#home'

#root :to => "pages#home"

#root :to => "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fav_item.rb
class FavItem < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fav_items_controller.rb
class FavItemsController < ApplicationController
  before_action :set_fav_item, only: %i[ show edit update destroy ]

  # GET /fav_items or /fav_items.json
  def index
    @fav_items = FavItem.all
  end

  # GET /fav_items/1 or /fav_items/1.json
  def show
  end

  # GET /fav_items/new
  def new
    @fav_item = FavItem.new
  end

  # GET /fav_items/1/edit
  def edit
  end

  # POST /fav_items or /fav_items.json
  def create
    @fav_item = FavItem.new(fav_item_params)

    respond_to do |format|
      if @fav_item.save
        format.html { redirect_to @fav_item, notice: "Fav item was successfully created." }
        format.json { render :show, status: :created, location: @fav_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fav_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fav_items/1 or /fav_items/1.json
  def update
    respond_to do |format|
      if @fav_item.update(fav_item_params)
        format.html { redirect_to @fav_item, notice: "Fav item was successfully updated." }
        format.json { render :show, status: :ok, location: @fav_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fav_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fav_items/1 or /fav_items/1.json
  def destroy
    @fav_item.destroy
    respond_to do |format|
      format.html { redirect_to fav_items_url, notice: "Fav item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fav_item
      @fav_item = FavItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fav_item_params
      params.require(:fav_item).permit(:name, :price, :category, :popularity)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  def home
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :category, :price, :popularity)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @all_items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:name])
  end

  #My own create function
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to @item
  end

  #private
  #def item_params
  #  params.require(:item).permit(:title, :text)
  #end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fav_items_helper.rb
module FavItemsHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/fav_items/_fav_item.html.erb
   <div>
   Crap


   <%=  object.name %>


   <%= form_with controller: @fav_item do |f| %>
        <% @fav_Item.create(object.attributes) %>
        <%= f.submit "Create", :class => "btn" %>
    <% end %>

</div>

app/views/fav_items/_form.html.erb
<%= form_with(model: fav_item) do |form| %>
  <% if fav_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fav_item.errors.count, "error") %> prohibited this fav_item from being saved:</h2>

      <ul>
        <% fav_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :popularity %>
    <%= form.text_field :popularity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fav_items/edit.html.erb
<h1>Editing Fav Item</h1>

<%= render 'form', fav_item: @fav_item %>

<%= link_to 'Show', @fav_item %> |
<%= link_to 'Back', fav_items_path %>

app/views/fav_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fav Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th>Popularity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fav_items.each do |fav_item| %>
      <tr>
        <td><%= fav_item.name %></td>
        <td><%= fav_item.price %></td>
        <td><%= fav_item.category %></td>
        <td><%= fav_item.popularity %></td>
        <td><%= link_to 'Show', fav_item %></td>
        <td><%= link_to 'Edit', edit_fav_item_path(fav_item) %></td>
        <td><%= link_to 'Destroy', fav_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fav Item', new_fav_item_path %>

app/views/fav_items/new.html.erb
<h1>New Fav Item</h1>

<%= render 'form', fav_item: @fav_item %>

<%= link_to 'Back', fav_items_path %>

app/views/fav_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fav_item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fav_item.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @fav_item.category %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @fav_item.popularity %>
</p>

<%= link_to 'Edit', edit_fav_item_path(@fav_item) %> |
<%= link_to 'Back', fav_items_path %>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :popularity %>
    <%= form.text_field :popularity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/home.html.erb
<h1>Wello Horld!</h1>


<div class="banner"></div>
<div class="row">
        <div class = "col-lg-4 mx-auto " style="background-color:grey;">
          <br>
          <h1 class="font-italic mx-auto mb-4" style="color: #2b2b2b; text-align:left; vertical-align: middle;"><strong>Fashion.com</strong></h1>
      </div>




<!-- Sample from that getting started tutorial -->

<h1>Listing Items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>


  <% @items.each do |currentItem| %>

    <tr>
      <td><%= currentItem.name %></td>
      <td><%= currentItem.price %></td>
      <td><%= currentItem.category %></td>
      <td><%= currentItem.popularity %></td>

      <td>
      <%= render :partial=>'fav_items/fav_item', :object=>currentItem  %>


      <%#= render 'fav_item', locals: { currentItem: categories }  %>
      <%#= render :partial=>'fav_item', :object=>currentItem  %>
      <%#= render 'fav_item', locals: {:collection => @all_items} %>

      <%#= render :partial=>"comments/comment", :object=>comment %>
      <%#= render 'fav_item', locals: {:i => i} %>
      <%#= render partial: 'show', locals: {profile: @profile} %>
      </td>

      According to the Rails docs. Please use
      <%#= render partial: "form", :locals => { :f => f  } %> or
      <%#= render "form", :f => f %> syntax.

 <%#=  render partial: "image_tag", locals: {image: i} %>
      <!-- #Try just saving one at all. -->

<%#= render :partial => "profiles/show", :collection => @profiles %>

on partial _show.html.erb

<%#= profile.fullname %>



    </tr>
  <% end %>




  #This is a favouriting practice.
  <tr>



  </tr>


</table>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Price</th>
      <th>Popularity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.category %></td>
        <td><%= item.price %></td>
        <td><%= item.popularity %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @item.popularity %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fashion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>